praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from status.views import index
from django.views.generic.base import RedirectView
from status.admin import admin_site
import status.urls as status
import profileLingin.urls as profile
import friendList.urls as friend
import stats.urls as stats

urlpatterns = [
    url(r'^admin/', admin_site.urls),
    url(r'^$', RedirectView.as_view(url='status/', permanent=True), name='root'),
    url(r'^status/', include(status, namespace='status')),
    url(r'^profile/', include(profile, namespace='profile')),
    url(r'^friend/', include(friend, namespace='friend')),
    url(r'^stats/', include(stats, namespace='stats')),
]

stats/urls.py
from django.conf.urls import url
from .views import index

# url for app

urlpatterns = [
    url(r'^$', index, name='index'),
    #  url(r'^add/$', add, name='add'),
]

status/urls.py
from django.conf.urls import url
from .views import index, add, comment, delete_comment, delete_status

# url for app

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', add, name='add'),
    url(r'^comment/(?P<id>\d)/$', comment, name='comment'),
    url(r'^delete/comment/(?P<id>\d)/$', delete_comment, name='delete_comment'),
    url(r'^delete/status/(?P<id>\d)/$', delete_status, name='delete_status'),
]

status/models.py
from django.db import models
from profileLingin.models import Member


class Status(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    status = models.TextField(max_length=140)


class Comment(models.Model):
    name = models.CharField(max_length=140, default="Anonymous")
    text = models.CharField(max_length=140)
    status = models.ForeignKey(Status)
    created_on = models.DateTimeField(auto_now_add=True)

status/forms.py
from django import forms


class StatusForm(forms.Form):
    status = forms.CharField(max_length=140)


class CommentForm(forms.Form):
    name = forms.CharField(max_length=140)
    text = forms.CharField(max_length=140)

status/views.py
from django.shortcuts import render, redirect
from .models import Status, Comment
from .forms import StatusForm, CommentForm
from profileLingin.models import Member


# Create your views here.
def index(request):
    response = {'name': Member.objects.get(id=1).name}
    status = Status.objects.all()
    response['commentform'] = CommentForm
    response['status'] = status
    return render(request, 'index.html', response)


def comment(request, id):
    if request.method == 'GET':
        response = {'commentform': CommentForm, 'status': id}
        return render(request, 'comment_page.html', response)
    elif request.method == 'POST':
        response = {'name': Member.objects.get(id=1).name}
        status = Status.objects.get(id=id)
        form = CommentForm(request.POST)
        response['form'] = form
        print(type(form))
        if form.is_valid():
            Comment.objects.create(name=form.cleaned_data['name'], text=form.cleaned_data['text'], status=status)
            return redirect('/status/')
        else:
            response['form'] = form
            return render(request, 'index.html', response)


def add(request):
    response = {'name': Member.objects.get(id=1).name}
    if request.method == 'POST':
        form = StatusForm(request.POST)
        response['form'] = form
        if form.is_valid():
            Status.objects.create(status=form.cleaned_data['status'])
            status = Status.objects.all()
            response['status'] = status
            return redirect('/status/')
        else:
            status = Status.objects.all()
            response['status'] = status
            response['form'] = form
            return render(request, 'index.html', response)
    return redirect('/status/')


def delete_comment(request, id):
    to_delete = Comment.objects.get(id=id)
    to_delete.delete()
    return redirect('/status/')


def delete_status(request, id):
    to_delete = Status.objects.get(id=id)
    to_delete.delete()
    return redirect('/status/')

status/templates/add_comment.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/status.css' %}" />
{% endblock %}

{% block content %}
    <!-- Main body -->
    <div class="container">
        <div class="row">
            <div class="col-sm-2">
                <h1>Komentar</h1>
            </div>
            <div class="col-sm-10">
                <div class="card">
                    <div class="card-block">
                        <h4 class="card-title"> Komentar </h4>
                        <!-- Form for new status -->
                        <form class="card-text" method="POST" action="{% url 'status:add' %}">
                            {% csrf_token %}
                            <input class="form-control" type="text" name="comment" />
                            <button class="btn btn-primary float-right">Post</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

status/templates/comment_page.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/status.css' %}" />
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-7">
                <h1 style="font-family: Bell MT; margin-top: 10px; font-weight: 550"> Add Comment </h1>
                <form action="{% url 'status:comment' status %}" method="POST">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-block">
                            <!-- Form for new name -->
                            <h5 class="card-title" style="font-family: Goudy Old Style"> Name </h5>
                                <input type="text" class="form-control" name="name" id="name" />
                            <h5 class="card-title" style="font-family: Goudy Old Style; margin-top: 10px"> Comment </h5>  
                                <input type="text" class="form-control" name="text" id="text" />
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary float-right" style="margin-top: 8px; margin-bottom: 20px" id="button">Add Comment</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

status/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/status.css' %}" />
{% endblock %}

{% block content %}
    <!-- Main body -->
    <div class="container">
        <div class="row">
            <div class="col-sm-7">
                <h3>Status</h3>
                <div class="card">
                    <div class="card-block">
                        <h4 class="card-title"> Update Status </h4>
                        <!-- Form for new status -->
                        <form class="card-text" method="POST" action="{% url 'status:add' %}">
                            {% csrf_token %}
                            <input class="form-control" name="status" id="status-field" title="status" placeholder="Enter Status..." />
                            <button class="btn btn-primary float-right" id="button" style="margin-top: 10px">Post</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Print errors if any -->
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}

    <!-- List all previous status -->
    <div class="container stasuses">
        {% for i in status reversed %}
            <div class="flex-item">
                <div class="status">
                    <img class="img-circle pic" src="https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.theimaginativeconservative.org%2Fwp-content%2Fuploads%2F2015%2F04%2Frobert-downey-jr.png&f=1" alt="me">
                    <h5> {{ name }} </h5>
                    {{ i.status }} <br/>
                    <sub> {{ i.date }} </sub>
                    <a class="btn btn-secondary float" id="button-delete" href="/status/delete/status/{{ i.id }}" style="margin-left: 10px">Delete</a>
                </div>
                <div class="comment-section">
{#                <p>Show comments..</p>#}
{#                <div class="hidden">#}
                    {% if i.comment_set.all %}
                        <div class="comment">
                            {% for comment in i.comment_set.all %}
                                <div class="asdsf" style="padding-bottom: 25px;">
                                    <h5> {{ comment.name }}</h5>
                                    {{ comment.text }} </br>
                                    <sub> {{ comment.created_on }} </sub>
                                    <a class="btn btn-secondary float-right" id="button-delete" href="/status/delete/comment/{{ comment.id }}">Delete</a>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}

                    <form action="{% url 'status:comment' i.id %}" method="GET" >
                        {% csrf_token %}
                        <button class="btn btn-secondary" type="submit" id="button" style="margin-left: 10px; margin-top: 5px">Add comment
                    </form>
{#                    <p>Hide comments..</p>#}
{#                </div>#}
                </div>
            </div>
        {% endfor %}
    </div>

    <!-- Scripts -->
{#    <script type="application/javascript">#}
{#        $( ".comment-section" ).click(function() {#}
{#            console.log(this.className+ " ")#}
{#            if ( this.tagName === "DIV" ){#}
{#                $( this.children ).toggleClass( "hidden" );#}
{#            }#}
{#            console.log("What the fuck");#}
{#        });#}
{#    </script>#}

{% endblock %}